### PR TITLE
Patch for issue gh-17

### PR DESCRIPTION
**Pull request by silentrob**
This adds three new token regular expressions. One for ID's, It should handle CRC8 and CRC32, as well as UUIDS and some token goggle was giving me.

A token for URLS and token for email addresses. The ID in my case was in the URL, so I added the ID before the URL one so it cascaded correctly. 

Ive also added a test to capture the intent of the issue and fix.

### CODE REVIEW

**Comment by dariusk** [comment]
Can you provide before/after performance tests? We used to capture this
stuff but it seriously reduced performance of the library so I ripped it
out.

**Comment by silentrob** [comment]
Good call, this update adds 2MS pref cost using your test.js on 750 Words.

**Comment by dariusk** [comment]
Sorry I kinda lost track on this issue but you can see it's failing a test. It breaks out the string `'https://docs.google.com/spreadsheets/d/19bdnznUXdHEOlp0Pnp9JY0rug6VuA2R3zK4AACdFzhE/edit?usp=sharing'` into `['https://docs.google.com/spreadsheets/d/19bdnznUXdHEOlp0Pnp9JY0rug6VuA2R3zK4AACdFzhE/edit?usp', '=sharing']`. It should keep it intact as a single url.

**Comment by silentrob** [comment]
Okay I think that should be an easy fix. I ran into an issue pulling my fork from github and had to create an npm package. I would be prefer to use your branch if you think this functionally is worth keeping.

**Comment by dariusk** [comment]
Yes, I'd like to keep this -- your comment about "2MS pref cost", that's 2 milliseconds, right? I'm okay with that if that's the case.

**Comment by silentrob** [comment]
Yes it is 2 milliseconds. I will true up the tests and update the ticket. Thanks for coming back to this.

**Comment by silentrob** [comment]
That should fix it.

**Comment by dariusk** [comment]
Thanks!

**Pull request merged**
